version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: adsistent_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  adsistent_bot:
    build: ./bot
    container_name: adsistent_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres_db

  n8n:
    image: docker.n8n.io/n8n/n8n
    container_name: adsistent_n8n
    restart: always
    environment:
      - N8N_HOST=n8n.domainanda.com
      - WEBHOOK_URL=https://n8n.domainanda.com
      - GENERIC_TIMEZONE=Asia/Jakarta
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_HOST=postgres_db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres_db

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: adsistent_tunnel
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

volumes:
  pg_data:
  n8n_data:
